micronaut:
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
  application:
    name: micronaut-jms-example

io:
  micronaut:
    configuration:
      jms:
        activemq:
          enabled: true
          connection-string: 'tcp://localhost:61616'

example:
  jms:
    destination: 'test'

datasources:
  default:
    url: 'jdbc:postgresql://localhost:9000/messages'
    username: 'postgres'
    password: 'docker'
    driverClassName: 'org.postgresql.Driver'

jpa:
  default:
    packages-to-scan:
      - 'io.micronaut.jms.example.repository.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update

flyway:
  datasources:
    default:
      locations: 'classpath:db/migrations'