name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get Version
        id: get_version
        run: |
          chmod +x gradlew
          VERSION="$(./gradlew properties -q | grep "version:" | awk '{print $2}').$(date +%s)"
          echo "Building for version ${VERSION} ..."
          echo "::set-output name=version::${VERSION}"
      - name: Build and Push Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ellpope/micronaut-jms-application:latest
            ellpope/micronaut-jms-application:${{ steps.get_version.outputs.version }}
      - name: Get Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
