name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ellpope/micronaut-jms-application:latest
            ellpope/micronaut-jms-application:$(date +%s)
      - name: Get Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
